[pytest]
generate_report_on_test = True
testpaths =
    tests
pythonpath = .
addopts = --browser chromium --tracing retain-on-failure --video=retain-on-failure --screenshot=only-on-failure --timeout 60 --html=report.html --self-contained-html -q -n auto