[pytest]
generate_report_on_test = True
testpaths =
    tests
pythonpath = .
addopts =
    # pytest-playwright options
    --browser chromium
    # enable for cross-browser runs (slower): --browser firefox --browser webkit
    --timeout 60
    -q -n auto
    
    # pytest-html options
    --tracing retain-on-failure
    --video=retain-on-failure
    --screenshot=only-on-failure 
    
    # pytest-html options
    --html=report.html
    --self-contained-html
    
    # pytest-allure options
    --alluredir allure-results 
    --clean-alluredir