name: Python package

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip'
      - name: Restore cached virtual environment
        uses: actions/cache/restore@v6
        with:
          key: venv-${{runner.os}}-${{steps.setup_python.outputs.python-version}}-${{ hashFiles('requirements.txt') }}
          path: .venv
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
      - name: Install browser binaries
        run: playwright install
      - name: Format code
        run: black --check .
      - name: Saved cached virtualenv
        uses: actions/cache/save@v6
        with:
          key: venv-${{runner.os}}-${{steps.setup_python.outputs.python-version}}-${{ hashFiles('requirements.txt') }}
          path: .venv
      - name: Test
        run: pytest
      - name: Upload artifacts on failure
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: failure-artifacts
          path: |-
            report.html
            allure-results/
            test-results/